# Generated by Django 5.1.1 on 2024-10-10 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b543283-d92e-4f2e-8eb5-adc639983f58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
