# Generated by Django 5.1.1 on 2024-10-10 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e18ed97e-09fc-409d-af5f-75497aea5458'), editable=False, primary_key=True, serialize=False),
        ),
    ]
