# Generated by Django 5.1.1 on 2024-10-10 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e8a85b4-3988-4c6f-8084-b8215c3dec47'), editable=False, primary_key=True, serialize=False),
        ),
    ]
