# Generated by Django 5.1.1 on 2024-10-10 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b3c1b1a-2250-4b45-b9a2-8c3fbbed08ee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
