# Generated by Django 5.1.1 on 2024-10-07 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8417a5a-4eea-490e-a198-39c3cb872e77'), editable=False, primary_key=True, serialize=False),
        ),
    ]
