# Generated by Django 5.1.1 on 2024-10-07 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57a5d889-7e7a-435d-b6e1-7c689f72cef6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
