# Generated by Django 5.1.1 on 2024-10-09 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf74b470-7f11-44ae-b829-9990b8aa7674'), editable=False, primary_key=True, serialize=False),
        ),
    ]
