# Generated by Django 5.1.1 on 2024-10-10 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b68f4e1-5759-48b6-8d04-cc8e135581b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
